server {
    listen 80;
    root /usr/share/nginx/html;

    # Кэширование статических ассетов (JS, CSS, шрифты, картинки)
    # Vite даёт хэши при сборке, поэтому безопасно
    location /assets/ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    # SSG-страницы и SPA fallback
    # NGINX будет пробовать отдать конкретную SSG страницу, если облом - SPA 200.html
    location / {
        try_files $uri $uri/index.html /200.html;
    }
}
