sonar.projectKey=ruftech-pass-backend
sonar.projectName=RufTECH Pass Backend

# Где исходники, где тесты
sonar.sources=app
sonar.tests=tests

sonar.python.version=3.12
sonar.python.coverage.reportPaths=coverage.xml

# Что не анализировать вообще
sonar.exclusions=**/alembic/**,**/__pycache__/**,**/certs/**,**/*.pyc

# Что не учитывать при подсчёте покрытия
# (миграции, конфиг, точка входа — их обычно не тестируют)
sonar.coverage.exclusions=tests/**,**/alembic/**,app/main.py,app/core/config.py

# Encoding
sonar.sourceEncoding=UTF-8