"""add service_url to password

Revision ID: c773c9d64a41
Revises: f61244ac4829
Create Date: 2026-04-09 17:35:16.443624

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c773c9d64a41'
down_revision: str | Sequence[str] | None = 'f61244ac4829'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('passwords', sa.Column('service_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('passwords', 'service_url')
    # ### end Alembic commands ###
