import { createThemeContract } from '@vanilla-extract/css'

export const vars = createThemeContract({
  palette: {
    greyBlack: null,
    greySelection: null,
    greyBorder: null,
    greySurface: null,
    black: null,
    light: null,
    lightBorder: null,
    white: null,
    whiteSub: null,
    blue: null,
    darkBlue: null,
    lightBlue: null,
    softBlue: null,
    deepBlue: null,
    green: null,
    darkGreen: null,
    deepGreen: null,
    red: null,
    darkRed: null,
    deepRed: null,
    amber: null,
    darkAmber: null,
    deepAmber: null,
    brightAmber: null,
  },
  color: {
    text: null,
    textMuted: null,
    background: null,
    backgroundTransparent: null,
    surface: null,
    border: null,
    primary: null,
    primaryHover: null,
    primaryPressed: null,
    success: null,
    successHover: null,
    successPressed: null,
    error: null,
    errorHover: null,
    errorPressed: null,
    warning: null,
    warningHover: null,
    warningPressed: null,
  },
  font: {
    size: {
      h1: null,
      h2: null,
      h3: null,
      regularText: null,
      descriptor: null,
      smallerText: null,
      altSmallerText: null,
      pagination: null,
      uiCaps: null,
      uiMini: null,
      uiRegular: null,
      uiMedium: null,
    },
    shorthand: {
      h1: null,
      h2: null,
      h3: null,
      regularText: null,
      pagination: null,
      descriptor: null,
      smallerText: null,
      altSmallerText: null,
      uiCaps: null,
      uiMini: null,
      uiRegular: null,
      uiMedium: null,
    },
    letterSpacing: {
      heading: null,
      pagination: null,
      smallerText: null,
      altSmallerText: null,
      uiCaps: null,
      uiMedium: null,
      uiRegular: null,
      uiMini: null,
    },
  },
})
