/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as LocaleRouteRouteImport } from './routes/$locale/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as LocaleIndexRouteImport } from './routes/$locale/index'
import { Route as LocaleDashboardRouteImport } from './routes/$locale/dashboard'
import { Route as LocaleAuthRouteImport } from './routes/$locale/auth'
import { Route as LocaleDashboardIndexRouteImport } from './routes/$locale/dashboard/index'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleRouteRoute = LocaleRouteRouteImport.update({
  id: '/$locale',
  path: '/$locale',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const LocaleIndexRoute = LocaleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleDashboardRoute = LocaleDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleAuthRoute = LocaleAuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleDashboardIndexRoute = LocaleDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleDashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/$locale/auth': typeof LocaleAuthRoute
  '/$locale/dashboard': typeof LocaleDashboardRouteWithChildren
  '/$locale/': typeof LocaleIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/$locale/dashboard/': typeof LocaleDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/$locale/auth': typeof LocaleAuthRoute
  '/$locale': typeof LocaleIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/$locale/dashboard': typeof LocaleDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/$locale/auth': typeof LocaleAuthRoute
  '/$locale/dashboard': typeof LocaleDashboardRouteWithChildren
  '/$locale/': typeof LocaleIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/$locale/dashboard/': typeof LocaleDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$locale'
    | '/auth'
    | '/dashboard'
    | '/$locale/auth'
    | '/$locale/dashboard'
    | '/$locale/'
    | '/dashboard/'
    | '/$locale/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/$locale/auth'
    | '/$locale'
    | '/dashboard'
    | '/$locale/dashboard'
  id:
    | '__root__'
    | '/'
    | '/$locale'
    | '/auth'
    | '/dashboard'
    | '/$locale/auth'
    | '/$locale/dashboard'
    | '/$locale/'
    | '/dashboard/'
    | '/$locale/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocaleRouteRoute: typeof LocaleRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale': {
      id: '/$locale'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/$locale/': {
      id: '/$locale/'
      path: '/'
      fullPath: '/$locale/'
      preLoaderRoute: typeof LocaleIndexRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/dashboard': {
      id: '/$locale/dashboard'
      path: '/dashboard'
      fullPath: '/$locale/dashboard'
      preLoaderRoute: typeof LocaleDashboardRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/auth': {
      id: '/$locale/auth'
      path: '/auth'
      fullPath: '/$locale/auth'
      preLoaderRoute: typeof LocaleAuthRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/dashboard/': {
      id: '/$locale/dashboard/'
      path: '/'
      fullPath: '/$locale/dashboard/'
      preLoaderRoute: typeof LocaleDashboardIndexRouteImport
      parentRoute: typeof LocaleDashboardRoute
    }
  }
}

interface LocaleDashboardRouteChildren {
  LocaleDashboardIndexRoute: typeof LocaleDashboardIndexRoute
}

const LocaleDashboardRouteChildren: LocaleDashboardRouteChildren = {
  LocaleDashboardIndexRoute: LocaleDashboardIndexRoute,
}

const LocaleDashboardRouteWithChildren = LocaleDashboardRoute._addFileChildren(
  LocaleDashboardRouteChildren,
)

interface LocaleRouteRouteChildren {
  LocaleAuthRoute: typeof LocaleAuthRoute
  LocaleDashboardRoute: typeof LocaleDashboardRouteWithChildren
  LocaleIndexRoute: typeof LocaleIndexRoute
}

const LocaleRouteRouteChildren: LocaleRouteRouteChildren = {
  LocaleAuthRoute: LocaleAuthRoute,
  LocaleDashboardRoute: LocaleDashboardRouteWithChildren,
  LocaleIndexRoute: LocaleIndexRoute,
}

const LocaleRouteRouteWithChildren = LocaleRouteRoute._addFileChildren(
  LocaleRouteRouteChildren,
)

interface DashboardRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocaleRouteRoute: LocaleRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
